spring.application.name=inscription

spring.datasource.url=jdbc:mysql://localhost:3306/inscriptiondb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8030

# Allow larger request bodies (e.g., base64 images in JSON)
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=-1

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=belhabibissra@gmail.com
spring.mail.password=pzjz hmor sfkj yisv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.debug=true