spring.application.name=gateway
server.port=8098

# EUREKA Registry
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# GLOBAL CORS CONFIGURATION
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=false

# Routes configuration
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[1].id=evaluation-service
spring.cloud.gateway.routes[1].uri=lb://evaluation
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/evaluation/**

spring.cloud.gateway.routes[2].id=inscription-service
spring.cloud.gateway.routes[2].uri=lb://inscription
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inscription/**

spring.cloud.gateway.routes[3].id=forum-service
spring.cloud.gateway.routes[3].uri=lb://forum
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/forum/**

# Log routes
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG

# Allow larger JSON payloads
spring.codec.max-in-memory-size=10MB