apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
        - name: evaluation
          image: __EVALUATION_IMAGE__
          imagePullPolicy: Always
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
          ports:
            - containerPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation
spec:
  selector:
    app: evaluation
  ports:
    - name: http
      port: 8020
      targetPort: 8020

