apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: __NOTEBOOK_IMAGE__
          imagePullPolicy: Always
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
          ports:
            - containerPort: 8030
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  selector:
    app: notebook
  ports:
    - name: http
      port: 8030
      targetPort: 8030

