apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - monitoring.yaml
images:
  - name: isra50/inscription
    newName: isra50/inscription
    newTag: "latest"
