spring.application.name=GestionCours
server.port=9090
server.servlet.context-path=/pidev4sae10
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/GestionCours-4SAE10?createDatabaseIfNotExist=true
spring.datasource.username=root
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# (Optionnel) Tolérer des payloads plus grands (si besoin)
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=-1