pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    environment {
        DOCKERHUB_USER = "saifdenden"
        IMAGE_NAME = "saifdenden/saifpidev"
        TAG = "${BUILD_NUMBER}"
        SERVICE_PATH = "backend/microservices/cours/GestionCours"
        GIT_REPO = "https://github.com/lamisbenhassine/Esprit-PI-4SAE10-2025-2026-SlangEngish.git"
        BRANCH = "gestion_cours"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/${BRANCH}"]],
                    userRemoteConfigs: [[
                        url: "${GIT_REPO}",
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }

        stage('Clean Install') {
            steps {
                dir("${SERVICE_PATH}") {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Tests + Coverage') {
            steps {
                dir("${SERVICE_PATH}") {
                    sh 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        dir("${SERVICE_PATH}") {
                            sh """
                                mvn sonar:sonar \
                                -Dsonar.login=$SONAR_TOKEN
                            """
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${SERVICE_PATH}") {
                    sh "docker build -t ${IMAGE_NAME}:${TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-token',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh """
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push ${IMAGE_NAME}:${TAG}
                    """
                }
            }
        }

        stage('Trigger CD Pipeline') {
            steps {
                build job: 'cd-pipeline',
                parameters: [
                    string(name: 'IMAGE_TAG', value: "${BUILD_NUMBER}")
                ]
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}